name: AutoNiche Pipeline

on:
  schedule:
    - cron: "15 5 * * *"  # codziennie ~07:15 czasu PL (5:15 UTC)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev deps (tests, lint, types)
        run: |
          pip install pytest ruff mypy

      - name: Ruff (lint)
        run: ruff check .

      - name: Mypy (types)
        run: mypy .

      - name: Pytest (unit tests)
        run: pytest -q

      - name: Generate content & site
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
        run: |
          python -m autoniche.main run-all

      - name: Convert Markdown posts to HTML
        run: |
          python - <<'PY'
import pathlib, markdown
root = pathlib.Path('docs/posts')
root.mkdir(parents=True, exist_ok=True)
for p in sorted(root.glob('*.md')):
    html = markdown.markdown(p.read_text(encoding='utf-8'), extensions=['extra'])
    (root / p.name.replace('.md', '.html')).write_text(f"<html><head><meta charset='utf-8'><link rel='stylesheet' href='../style.css'></head><body>{html}</body></html>", encoding='utf-8')
PY

      - name: Add basic CSS
        run: |
          cat > docs/style.css <<'CSS'
body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,Arial,sans-serif;max-width:760px;margin:2rem auto;padding:0 1rem;line-height:1.6}
h1,h2,h3{line-height:1.25}
pre{background:#f6f8fa;padding:1rem;overflow:auto}
code{background:#f6f8fa;padding:.2rem .4rem;border-radius:4px}
hr{border:0;border-top:1px solid #eee;margin:2rem 0}
CSS

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/ data/state.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto publish: $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
